### ISSUE TITLE
Unable to connect to remote machine when using fetch_results command

### ISSUE THREAD

**Issue by NicolasMonnier** [djgroen/FabSim3#95] opened 2019-03-27 14:03 UTC
When I tried to fetch the results of my job on the remote machie using the following command : `fab <remote_machine> fetch_results`, I wasn't able to connect to the machine.

The current command used in fab.py is : 

`"rsynx -pthrvz $username@$remote:$job_results/%s $job_results_local" % regex`

it finally worked when I change it to : 

`"rsynx -pthrvz -e 'ssh -p $port' $username@$remote:$job_results/%s $job_results_local" % regex`

My remote_machine was Genji, wich I added manualy.

**Comment by arabnejad** [comment] 2019-03-27 14:16
And what was the port number in your configuration??

**Comment by NicolasMonnier** [comment] 2019-03-27 14:21
The port number was 8522

**Comment by arabnejad** [comment] 2019-03-27 14:25
Ok, give me a time, I'll do some tests and update the code, could you please send your config file for Genji

**Comment by arabnejad** [comment] 2019-03-27 14:28
I think the problem is the specific port number which is different with default port for rsynx,

**Comment by arabnejad** [comment] 2019-04-01 12:41
Hi @NicolasMonnier 
please check `featch_result` command
I used `--port=$port` instead of ```-e `ssh -p $port` ```

**Comment by arabnejad** [comment] 2019-04-05 12:22
Fixed by [commit](https://github.com/djgroen/FabSim3/commit/75ab8e4157110d64d1735fc8f1ca466b1c90a114
)

**Closed by arabnejad** 2019-04-05 12:22 UTC
