### ISSUE TITLE
Install_app:QCG-PilotJob,virtual_env=True crashes 

### ISSUE THREAD

**Issue by cspgdds** [djgroen/FabSim3#163] opened 2020-01-21 15:42 UTC
Code crashed when running 
**fab qcg install_app:QCG-PilotJob,virtual_env=True**
```
[plgdianas10@eagle.man.poznan.pl] Executing task 'install_app'
[localhost] local: mkdir -p /home/csstdds/Codes/FabSim3/tmp_app
[localhost] local: pip3 download --no-binary=:all: -d /home/csstdds/Codes/FabSim3/tmp_app pandas
Collecting pandas
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/pandas-0.25.3.tar.gz
Collecting python-dateutil>=2.6.1
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/python-dateutil-2.8.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pytz>=2017.2
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/pytz-2019.3.tar.gz
Collecting numpy>=1.13.3
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/numpy-1.18.1.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmptbqkp6mp
         cwd: /tmp/pip-download-w_e6ktwz/numpy
    Complete output (38 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_bit_generator.pyx
    Traceback (most recent call last):
      File "/tmp/pip-download-w_e6ktwz/numpy/tools/cythonize.py", line 238, in <module>
        main()
      File "/tmp/pip-download-w_e6ktwz/numpy/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/tmp/pip-download-w_e6ktwz/numpy/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-download-w_e6ktwz/numpy/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-download-w_e6ktwz/numpy/tools/cythonize.py", line 79, in process_pyx
        VENDOR, required_version))
    RuntimeError: Building NumPy requires Cython >= 0.29.14
    Running from numpy source directory.
    setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Traceback (most recent call last):
      File "/home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/csstdds/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/home/csstdds/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/home/csstdds/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 488, in <module>
        setup_package()
      File "setup.py", line 469, in setup_package
        generate_cython()
      File "setup.py", line 275, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmptbqkp6mp Check the logs for full command output.

Fatal error: local() encountered an error (return code 1) while executing 'pip3 download --no-binary=:all: -d /home/csstdds/Codes/FabSim3/tmp_app pandas'

Aborting.

```

OR

**fab eagle_hidalgo install_app:QCG-PilotJob,virtual_env=True**
```
[dianas@eagle.man.poznan.pl] Executing task 'install_app'
[localhost] local: mkdir -p /home/csstdds/Codes/FabSim3/tmp_app
[localhost] local: pip3 download --no-binary=:all: -d /home/csstdds/Codes/FabSim3/tmp_app pandas
Collecting pandas
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/pandas-0.25.3.tar.gz
Collecting python-dateutil>=2.6.1
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/python-dateutil-2.8.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pytz>=2017.2
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/pytz-2019.3.tar.gz
Collecting numpy>=1.13.3
  File was already downloaded /home/csstdds/Codes/FabSim3/tmp_app/numpy-1.18.1.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_5ywjy6k
         cwd: /tmp/pip-download-i70m_lr_/numpy
    Complete output (38 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_bit_generator.pyx
    Traceback (most recent call last):
      File "/tmp/pip-download-i70m_lr_/numpy/tools/cythonize.py", line 238, in <module>
        main()
      File "/tmp/pip-download-i70m_lr_/numpy/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/tmp/pip-download-i70m_lr_/numpy/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-download-i70m_lr_/numpy/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-download-i70m_lr_/numpy/tools/cythonize.py", line 79, in process_pyx
        VENDOR, required_version))
    RuntimeError: Building NumPy requires Cython >= 0.29.14
    Running from numpy source directory.
    setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Traceback (most recent call last):
      File "/home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/csstdds/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/home/csstdds/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/home/csstdds/.local/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 488, in <module>
        setup_package()
      File "setup.py", line 469, in setup_package
        generate_cython()
      File "setup.py", line 275, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/csstdds/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp_5ywjy6k Check the logs for full command output.

Fatal error: local() encountered an error (return code 1) while executing 'pip3 download --no-binary=:all: -d /home/csstdds/Codes/FabSim3/tmp_app pandas'

Aborting.
```

**Comment by arabnejad** [comment] 2020-01-27 12:03
@cspgdds , since that the problem is caused by some pip3 or python issues on your local machine, I think we can close this issue

**Closed by arabnejad** 2020-01-27 12:03 UTC
